var strVar="";

strVar += "                <!-- BISOGNO -->";
strVar += "                <div class=\"form-group form-group-lg config-row bisogno\">";
strVar += "                    <span class=\"testo-domanda\">Vorrei<\/span>";
strVar += "                    <select class=\"form-control\" id=\"bisogno\" data-array=\"0\">";
strVar += "                        <option disabled selected value><\/option>";
strVar += "                        <option value=\"capitale\">garantire il capitale<\/option>";
strVar += "                        <option value=\"mercati_finanziari\">cogliere le opportunit&agrave; dei mercati<\/option>";
strVar += "                    <\/select>";
strVar += "                    <span class=\"testo-domanda\">,<\/span>";
strVar += "                <\/div>";
strVar += "";
strVar += "";
strVar += "                <!-- ----------------";
strVar += "                ------ CAPITALE -----";
strVar += "                ----------------- -->";
strVar += "";
strVar += "                <!-- RISPARMIATO SI\/NO -->";
strVar += "                <div class=\"form-group form-group-lg config-row capitale risparmiato\">";
strVar += "                    <span class=\"testo-domanda\">che<\/span>";
strVar += "                    <select class=\"form-control\" id=\"capitale_risparmiato\" data-array=\"1\">";
strVar += "                        <option disabled selected value><\/option>";
strVar += "                        <option value=\"gia_risparmiato\">ho gi&agrave; risparmiato<\/option>";
strVar += "                        <option value=\"non_risparmiato\">risparmier&ograve; nel tempo<\/option>";
strVar += "                    <\/select>";
strVar += "                <\/div>";
strVar += "";
strVar += "                        <!-- GIA' RISPARMIATO -> LIQUIDAZIONE -->";
strVar += "                        <div class=\"form-group form-group-lg config-row capitale liquidazione_gia_risparmiato\">";
strVar += "                            <span class=\"testo-domanda\">ed avere una liquidazione degli interessi<\/span>";
strVar += "                            <select class=\"form-control\" id=\"liquidazione_gia_risparmiato\" data-array=\"2\">";
strVar += "                                <option disabled selected value><\/option>";
strVar += "                                <option value=\"periodica\">periodica<\/option>";
strVar += "                                <option value=\"a_scadenza\">a scadenza<\/option>";
strVar += "                            <\/select>";
strVar += "                        <\/div>";
strVar += "";
strVar += "                        <!-- NON RISPARMIATO -> LIQUIDAZIONE -->";
strVar += "                        <div class=\"form-group form-group-lg config-row capitale liquidazione_non_risparmiato\">";
strVar += "                            <span class=\"testo-domanda\">ed avere una liquidazione degli interessi<\/span>";
strVar += "                            <select class=\"form-control\" id=\"liquidazione_non_risparmiato\" data-array=\"2\">";
strVar += "                                <option disabled selected value><\/option>";
strVar += "                                <option value=\"periodica\">periodica<\/option>";
strVar += "                                <option value=\"a_scadenza\">a scadenza<\/option>";
strVar += "                            <\/select>";
strVar += "                        <\/div>";
strVar += "";
strVar += "";
strVar += "";
strVar += "                <!-- --------------------------";
strVar += "                ------ MERCATI FINANZIARI -----";
strVar += "                --------------------------- -->";
strVar += "";
strVar += "                <!-- protezione assicurativa SI\/NO -->";
strVar += "                <div class=\"form-group form-group-lg config-row mercati_finanziari protezione_assicurativa\">";
strVar += "                    ";
strVar += "                    <select class=\"form-control\" id=\"protezione_assicurativa\" data-array=\"1\">";
strVar += "                        <option disabled selected value><\/option>";
strVar += "                        <option value=\"protezione_assicurativa\">usufruire<\/option>";
strVar += "                        <option value=\"no_protezione_assicurativa\">non usufruire<\/option>";
strVar += "                    <\/select>";
strVar += "                    <span class=\"testo-domanda\">di una protezione assicurativa<\/span>";
strVar += "                <\/div>";
strVar += "";
strVar += "";
strVar += "                        <!-- gestione capitale -->";
strVar += "                        <div class=\"form-group form-group-lg config-row mercati_finanziari gestione_capitale_ass\">";
strVar += "                            <span class=\"testo-domanda\">e<\/span>";
strVar += "                            <select class=\"form-control\" id=\"gestione_capitale_ass\" data-array=\"2\">";
strVar += "                                <option disabled selected value><\/option>";
strVar += "                                <option value=\"proteggere_capitale\">proteggere parte del<\/option>";
strVar += "                                <option value=\"gestione_dinamica_capitale\">avere una gestione flessibile del<\/option>";
strVar += "                            <\/select>";
strVar += "                            <span class=\"testo-domanda\"> mio capitale<\/span>";
strVar += "                        <\/div>";
strVar += "";
strVar += "                        <div class=\"form-group form-group-lg config-row mercati_finanziari gestione_capitale_no_ass\">";
strVar += "                            <span class=\"testo-domanda\">e<\/span>";
strVar += "                            <select class=\"form-control\" id=\"gestione_capitale_no_ass\" data-array=\"2\">";
strVar += "                                <option disabled selected value><\/option>";
strVar += "                                <option value=\"proteggere_capitale\">proteggere il<\/option>";
strVar += "                                <option value=\"gestione_dinamica_capitale\">avere una gestione flessibile del<\/option>";
strVar += "                            <\/select>";
strVar += "                            <span class=\"testo-domanda\"> mio capitale<\/span>";
strVar += "                        <\/div>";
strVar += "";





$('.configuratore-risultato-prodotti').html(strVar);
