var strVar="";
strVar += "";
strVar += "<div class=\"hidden-xs config-container-wrap\">";
strVar += "    <h2>Necessiti di un aiuto specifico?<\/h2>";
strVar += "    <div class=\"hidden-xs assistenza-domande\">";
strVar += "        <div class=\"form-group form-group-lg config-row bisogno\">";
strVar += "            <span class=\"testo-domanda\">Ho bisogno dell'assistenza di<\/span>";
strVar += "            <select class=\"form-control\" id=\"bisogno\">";
strVar += "                <option disabled selected value><\/option>";
strVar += "                <option value=\"bancoposta\">BancoPosta<\/option>";
strVar += "                <option value=\"postevita\">Postevita<\/option>";
strVar += "                <option value=\"servizipostali\">Servizi Postali<\/option>";
strVar += "                <option value=\"postemobile\">Postemobile<\/option>";
strVar += "                <option value=\"postesalute\">Postesalute<\/option>";
strVar += "                <option value=\"postepay\">Postepay<\/option>";
strVar += "                <option value=\"mistralair\">Mistral Air<\/option>";
strVar += "            <\/select>";
strVar += "        <\/div>";
strVar += "        <!-- BANCOPOSTA -->";
strVar += "        <div class=\"form-group form-group-lg config-row generico bancoposta bancoposta_tipo_assistenza\">";
strVar += "            <span class=\"testo-domanda\">per<\/span>";
strVar += "            <select class=\"form-control\" id=\"bancoposta_tipo_assistenza\">";
strVar += "                <option disabled selected value><\/option>";
strVar += "                <option value=\"bancoposta_assistenza_generica\">informazioni e assistenza generica<\/option>";
strVar += "                <option value=\"bancoposta_contestazioni_addebito\">informazioni o per segnalare contestazioni di addebito<\/option>";
strVar += "                <option value=\"bancoposta_smarrimento_furto_carta\">smarrimento o furto della carta<\/option>";
strVar += "            <\/select>";
strVar += "        <\/div>";
strVar += "        <div class=\"form-group form-group-lg config-row bancoposta bancoposta_assistenza_generica_dove\">";
strVar += "            <span class=\"testo-domanda\">da<\/span>";
strVar += "            <select class=\"form-control\" id=\"bancoposta_assistenza_generica_dove\">";
strVar += "                <option disabled selected value><\/option>";
strVar += "                <option value=\"generica_italia\">Italia<\/option>";
strVar += "                <option value=\"generica_estero\">estero<\/option>";
strVar += "            <\/select>";
strVar += "        <\/div>";
strVar += "        <div class=\"form-group form-group-lg config-row bancoposta bancoposta_contestazioni_addebito_carta\">";
strVar += "            <span class=\"testo-domanda\">per<\/span>";
strVar += "            <select class=\"form-control\" id=\"bancoposta_contestazioni_addebito_carta\">";
strVar += "                <option disabled selected value><\/option>";
strVar += "                <option value=\"contestazioni_uno\">Carta BancoPosta Classica e Credit Easy<\/option>";
strVar += "                <option value=\"contestazioni_due\">Carta BancoPosta Oro<\/option>";
strVar += "                <option value=\"contestazioni_tre\">Carta BancoPosta Ricaricabile<\/option>";
strVar += "                <option value=\"contestazioni_quattro\">Carta Oro American Express<\/option>";
strVar += "                <option value=\"contestazioni_cinque\">Carta BancoPosta Pi&ugrave;<\/option>";
strVar += "            <\/select>";
strVar += "        <\/div>";
strVar += "        <div class=\"form-group form-group-lg config-row bancoposta bancoposta_smarrimento_furto_carta\">";
strVar += "            <span class=\"testo-domanda\">per<\/span>";
strVar += "            <select class=\"form-control\" id=\"bancoposta_smarrimento_furto_carta\">";
strVar += "                <option disabled selected value><\/option>";
strVar += "                <option value=\"furto_uno\">Postepay<\/option>";
strVar += "                <option value=\"furto_due\">Carta BancoPosta Oro<\/option>";
strVar += "                <option value=\"furto_tre\">Carta BancoPosta Ricaricabile<\/option>";
strVar += "                <option value=\"furto_quattro\">Carta Oro American Express<\/option>";
strVar += "                <option value=\"furto_cinque\">Carta BancoPosta Pi&ugrave;<\/option>";
strVar += "                <option value=\"furto_sei\">Carta BancoPosta Pi&ugrave;<\/option>";
strVar += "            <\/select>";
strVar += "        <\/div>";
strVar += "        <!-- POSTEVITA -->";
strVar += "        <div class=\"form-group form-group-lg config-row postevita postevita_tipo_assistenza\">";
strVar += "            <span class=\"testo-domanda\">per<\/span>";
strVar += "            <select class=\"form-control\" id=\"postevita_tipo_assistenza\">";
strVar += "                <option disabled selected value><\/option>";
strVar += "                <option value=\"n_postevita\">Postevita<\/option>";
strVar += "                <option value=\"n_posteassicura\">Posteassicura<\/option>";
strVar += "            <\/select>";
strVar += "        <\/div>";
strVar += "        <!-- POSTEMOBILE -->";
strVar += "        <div class=\"form-group form-group-lg config-row generico postemobile postemobile_tipo_assistenza\">";
strVar += "            <span class=\"testo-domanda\">per<\/span>";
strVar += "            <select class=\"form-control\" id=\"postemobile_tipo_assistenza\">";
strVar += "                <option disabled selected value><\/option>";
strVar += "                <option value=\"servizio_clienti\">Servizio Clienti<\/option>";
strVar += "                <option value=\"non_udenti\">Servizio Clienti non udenti<\/option>";
strVar += "                <option value=\"servizio_faidate\">Servizio fai da te<\/option>";
strVar += "            <\/select>";
strVar += "        <\/div>";
strVar += "        <div class=\"form-group form-group-lg config-row postemobile postemobile_servizioclienti_dove\">";
strVar += "            <span class=\"testo-domanda\">da<\/span>";
strVar += "            <select class=\"form-control\" id=\"postemobile_servizioclienti_dove\">";
strVar += "                <option disabled selected value><\/option>";
strVar += "                <option value=\"servizioclienti_italia\">Italia<\/option>";
strVar += "                <option value=\"servizioclienti_estero\">estero<\/option>";
strVar += "            <\/select>";
strVar += "        <\/div>";
strVar += "        <div class=\"form-group form-group-lg config-row postemobile postemobile_nonudenti_come\">";
strVar += "            <span class=\"testo-domanda\">tramite<\/span>";
strVar += "            <select class=\"form-control\" id=\"postemobile_nonudenti_come\">";
strVar += "                <option disabled selected value><\/option>";
strVar += "                <option value=\"nonudenti_email\">e-mail<\/option>";
strVar += "                <option value=\"nonudenti_fax\">fax<\/option>";
strVar += "                <option value=\"nonudenti_sms\">SMS<\/option>";
strVar += "            <\/select>";
strVar += "        <\/div>";
strVar += "        <div class=\"form-group form-group-lg config-row postemobile postemobile_nonudenti_fax_dove\">";
strVar += "            <span class=\"testo-domanda\">da<\/span>";
strVar += "            <select class=\"form-control\" id=\"postemobile_nonudenti_fax_dove\">";
strVar += "                <option disabled selected value><\/option>";
strVar += "                <option value=\"nonudenti_fax_italia\">Italia<\/option>";
strVar += "                <option value=\"nonudenti_fax_estero\">estero<\/option>";
strVar += "            <\/select>";
strVar += "        <\/div>";
strVar += "        <!-- POSTEPAY -->";
strVar += "        <div class=\"form-group form-group-lg config-row generico postepay postepay_tipo_assistenza\">";
strVar += "            <span class=\"testo-domanda\">per<\/span>";
strVar += "            <select class=\"form-control\" id=\"postepay_tipo_assistenza\">";
strVar += "                <option disabled selected value><\/option>";
strVar += "                <option value=\"postepay_informazioni\">Informazioni, rinnovo e assistenza<\/option>";
strVar += "                <option value=\"postepay_blocco\">Blocco carta per furto o smarrimento<\/option>";
strVar += "            <\/select>";
strVar += "        <\/div>";
strVar += "        <div class=\"form-group form-group-lg config-row generico postepay postepay_informazioni_dove\">";
strVar += "            <span class=\"testo-domanda\">da<\/span>";
strVar += "            <select class=\"form-control\" id=\"postepay_informazioni_dove\">";
strVar += "                <option disabled selected value><\/option>";
strVar += "                <option value=\"postepay_info_italia\">Italia<\/option>";
strVar += "                <option value=\"postepay_info_estero\">estero<\/option>";
strVar += "            <\/select>";
strVar += "        <\/div>";
strVar += "        <div class=\"form-group form-group-lg config-row generico postepay postepay_blocco_dove\">";
strVar += "            <span class=\"testo-domanda\">da<\/span>";
strVar += "            <select class=\"form-control\" id=\"postepay_blocco_dove\">";
strVar += "                <option disabled selected value><\/option>";
strVar += "                <option value=\"postepay_blocco_italia\">Italia<\/option>";
strVar += "                <option value=\"postepay_blocco_estero\">estero<\/option>";
strVar += "            <\/select>";
strVar += "        <\/div>";
strVar += "        <!-- MISTRALAIR -->";
strVar += "        <div class=\"form-group form-group-lg config-row generico mistralair mistralair_tipo_assistenza\">";
strVar += "            <span class=\"testo-domanda\">tramite<\/span>";
strVar += "            <select class=\"form-control\" id=\"mistralair_tipo_assistenza\">";
strVar += "                <option disabled selected value><\/option>";
strVar += "                <option value=\"mistralair_email\">e-mail<\/option>";
strVar += "                <option value=\"mistralair_fax\">fax<\/option>";
strVar += "                <option value=\"mistralair_tel\">telefono<\/option>";
strVar += "                <option value=\"mistralair_posta\">posta<\/option>";
strVar += "            <\/select>";
strVar += "        <\/div>";
strVar += "    <\/div>";
strVar += "";
strVar += "";
strVar += "";
strVar += "";
strVar += "    <div class=\"assistenza-numeri\" style=\"margin-top:40px;\">";
strVar += "        <!-- bancoposta -->";
strVar += "        <div class=\"numero generica_italia\">";
strVar += "            <div class=\"content\"><a href=\"tel:800003322\">800003322<\/a><\/div>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero generica_estero\">";
strVar += "            <div class=\"content\"><a href=\"tel:+390282443333\">+390282443333<\/a><\/div>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero contestazioni_uno\">";
strVar += "            <div class=\"content\"><a href=\"tel:0432744255\">0432744255<\/a><\/div>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero contestazioni_due\">";
strVar += "            <div class=\"content\"><a href=\"tel:0432744264\">0432744264<\/a><\/div>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero contestazioni_tre\">";
strVar += "            <div class=\"content\"><a href=\"tel:800.397206\">800.397206<\/a><\/div>";
strVar += "            <span>(chiamate da telefono fisso)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero contestazioni_tre\">";
strVar += "            <div class=\"content\"><a href=\"tel:02.30352001\">02.30352001<\/a><\/div>";
strVar += "            <span>(chiamate da cellulare)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero contestazioni_quattro\">";
strVar += "            <div class=\"content\"><a href=\"tel:06.72.280.735\">06.72.280.735<\/a><\/div>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero contestazioni_cinque\">";
strVar += "            <div class=\"content\"><a href=\"tel:800.00.33.22\">800.00.33.22<\/a><\/div>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero furto_uno\">";
strVar += "            <div class=\"content\"><a href=\"tel:800.90.21.22\">800.90.21.22<\/a><\/div>";
strVar += "            <span>(dall'Italia)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero furto_uno\">";
strVar += "            <div class=\"content\"><a href=\"tel:+39.049.2100.149\">+39.049.2100.149<\/a><\/div>";
strVar += "            <span>(dall'estero)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero furto_due\">";
strVar += "            <div class=\"content\"><a href=\"tel:800.652.653\">800.652.653<\/a><\/div>";
strVar += "            <span>(dall'Italia)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero furto_due\">";
strVar += "            <div class=\"content\"><a href=\"tel:+39.04.92100148\">+39.04.92100148<\/a><\/div>";
strVar += "            <span>(dall'estero)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero furto_tre\">";
strVar += "            <div class=\"content\"><a href=\"tel:800.207.167\">800.207.167<\/a><\/div>";
strVar += "            <span>(dall'Italia)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero furto_tre\">";
strVar += "            <div class=\"content\"><a href=\"tel:0039.0432.744106\">0039.0432.744106<\/a><\/div>";
strVar += "            <span>(dall'estero)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero furto_quattro\">";
strVar += "            <div class=\"content\"><a href=\"tel:800.822.056\">800.822.056<\/a><\/div>";
strVar += "            <span>(dall'Italia)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero furto_quattro\">";
strVar += "            <div class=\"content\"><a href=\"tel:0039.02.6084.3768\">0039.02.6084.3768<\/a><\/div>";
strVar += "            <span>(dall'estero)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero furto_cinque\">";
strVar += "            <div class=\"content\"><a href=\"tel:800.822.056\">800.822.056<\/a><\/div>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero furto_sei\">";
strVar += "            <div class=\"content\"><a href=\"tel:06.72.900.347\">06.72.900.347<\/a><\/div>";
strVar += "            <span>(dall'Italia)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero furto_sei\">";
strVar += "            <div class=\"content\"><a href=\"tel:011.800.263.92.279\">011.800.263.92.279<\/a><\/div>";
strVar += "            <span>(da USA, Canada e Australia)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero furto_sei\">";
strVar += "            <div class=\"content\"><a href=\"tel:018.001.231.690\">018.001.231.690<\/a><\/div>";
strVar += "            <span>(dal Messico)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero furto_sei\">";
strVar += "            <div class=\"content\"><a href=\"tel:+800.263.92.279\">+800.263.92.279<\/a><\/div>";
strVar += "            <span>(dagli altri paesi)<\/span>";
strVar += "        <\/div>";
strVar += "        <!-- Postevita -->";
strVar += "        <div class=\"numero n_postevita\">";
strVar += "            <div class=\"content\"><a href=\"tel:800.31.61.81\">800.31.61.81<\/a><\/div>";
strVar += "            <span>(numero attivo dal luned&igrave; al venerd&igrave; dalle 8:00 alle 20:00, sabato dalle 8:00 alle 14:00)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero n_posteassicura\">";
strVar += "            <div class=\"content\"><a href=\"tel:800.13.18.11\">800.13.18.11<\/a><\/div>";
strVar += "            <span>(numero attivo dal luned&igrave; al venerd&igrave; dalle 8:00 alle 20:00, sabato dalle 8:00 alle 14:00)<\/span>";
strVar += "        <\/div>";
strVar += "        <!-- Servizi Postali -->";
strVar += "        <div class=\"numero n_servizipostali\">";
strVar += "            <div class=\"content\">";
strVar += "                <a href=\"tel:+39 02.82.44.33.99\">+39 02.82.44.33.99<\/a>";
strVar += "            <\/div>";
strVar += "            <span>(numero attivo dal luned&igrave; al sabato dalle 8:00 alle 20:00)<\/span>";
strVar += "        <\/div>";
strVar += "        <!-- Postemobile -->";
strVar += "        <div class=\"numero servizioclienti_italia\">";
strVar += "            <div class=\"content\"><a href=\"tel:160\">160<\/a><\/div>";
strVar += "            <span>(gratuito dai numeri PosteMobile e dalla rete fissa Telecom Italia, attivo tutti i giorni dalle 7.00 alle 24.00 per assistenza tecnica, commerciale e amministrativa e 24 ore su 24 per furto\\/smarrimento)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero servizioclienti_estero\">";
strVar += "            <div class=\"content\"><a href=\"tel:+39 37.70.00.01.60\">+39 37.70.00.01.60<\/a><\/div>";
strVar += "            <span>(la chiamata ha il costo di una normale chiamata dall'estero verso l'Italia.)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero nonudenti_email\">";
strVar += "            <div class=\"content\"><a href=\"mailto:servizioclienti_nonudenti@postemobile.it\">servizioclienti_nonudenti@postemobile.it<\/a><\/div>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero nonudenti_fax_italia\">";
strVar += "            <div class=\"content\"><a href=\"tel:800 185 111\">800 185 111<\/a><\/div>";
strVar += "            <span>(gratuito)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero nonudenti_fax_estero\">";
strVar += "            <div class=\"content\"><a href=\"tel:+39 06.98.68.26.21\">+39 06.98.68.26.21<\/a><\/div>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero nonudenti_sms\">";
strVar += "            <div class=\"content\"><a href=\"tel:40.71.164\">+40.71.164<\/a><\/div>";
strVar += "            <span>(gratuito dall'Italia e dall'estero)<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero servizio_faidate\">";
strVar += "            <div class=\"content\"><a href=\"tel:40.12.12\">40.12.12<\/a><\/div>";
strVar += "            <span>attivo tutti i giorni 24 ore su 24 numero gratuito accessibile solo da SIM PosteMobile<\/span>";
strVar += "        <\/div>";
strVar += "        <!-- Postesalute -->";
strVar += "        <div class=\"numero n_postesalute\">";
strVar += "            <div class=\"content\"><a href=\"tel:800.556.670\">800.556.670<\/a><\/div>";
strVar += "            <span>(con operatore dal luned&igrave; al venerd&igrave;, dalle 09:00 alle 18:00 e il sabato dalle 09:00 alle 17:00 festivi esclusi. La chiamata &egrave; gratuita)<\/span>";
strVar += "        <\/div>";
strVar += "        <!-- Postepay -->";
strVar += "        <div class=\"numero postepay_info_italia\">";
strVar += "            <div class=\"content\"><a href=\"tel:800.00.33.22\">800.00.33.22<\/a><\/div>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero postepay_info_estero\">";
strVar += "            <div class=\"content\"><a href=\"tel:+39 02.82.44.33.33\">+39 02.82.44.33.33<\/a><\/div>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero postepay_blocco_italia\">";
strVar += "            <div class=\"content\"><a href=\"tel:800.90.21.22\">800.90.21.22<\/a><\/div>";
strVar += "            <span>il servizio &egrave; attivo h24<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero postepay_blocco_estero\">";
strVar += "            <div class=\"content\"><a href=\"tel:+39 049.21.00.149\">+39 049.21.00.149<\/a><\/div>";
strVar += "            <span>il servizio &egrave; attivo h24<\/span>";
strVar += "        <\/div>";
strVar += "        <!-- Mistral Air -->";
strVar += "        <div class=\"numero mistralair_email\">";
strVar += "            <div class=\"content\"><a href=\"mailto:infomistralair@posteitaliane.it\">infomistralair@posteitaliane.it<\/a><\/div>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero mistralair_fax\">";
strVar += "            <div class=\"content\"><a href=\"tel:+39 06.59.19.567\">+39 06.59.19.567<\/a><\/div>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero mistralair_tel\">";
strVar += "            <div class=\"content\"><a href=\"tel:+39 06.96.66.33.33\">+39 06.96.66.33.33<\/a><\/div>";
strVar += "            <span>Da luned&igrave; a venerd&igrave; 9:00 - 13:00 e 14:00 - 18:00<\/span>";
strVar += "        <\/div>";
strVar += "        <div class=\"numero mistralair_posta\">";
strVar += "            <div class=\"content\"><a href=\"javascript:void(0)\">Viale Lincoln, 3 00144 Roma (RM) - Italia<\/a><\/div>";
strVar += "        <\/div>";
strVar += "    <\/div>";
strVar += "<\/div>";
strVar += "";

document.write(strVar);