var strVar="";
strVar += "<div class=\"visible-xs config-container-wrap mobile\">";
strVar += "    <h2>Necessiti di un aiuto specifico?<\/h2>";
strVar += "    <div class=\"assistenza-numeri_mobile\">";
strVar += "        <div class=\"panel-group panel-group-unique panel-group-accordion\" id=\"accordionunique\" role=\"tablist\" aria-multiselectable=\"true\">";
strVar += "            <!-- BancoPosta -->";
strVar += "            <div class=\"panel\">";
strVar += "                <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">";
strVar += "                    <h4 class=\"panel-title\">";
strVar += "                        <a class=\"accordion-toggle collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordionunique\" href=\"#collapse01\" aria-expanded=\"false\" aria-controls=\"collapseOne\">BancoPosta<\/a>";
strVar += "                    <\/h4>";
strVar += "                <\/div>";
strVar += "                <div id=\"collapse01\" class=\"panel-collapse collapse nojs-block\" role=\"tabpanel\" aria-labelledby=\"headingOne\">";
strVar += "                    <div class=\"panel-body\">";
strVar += "                        <div class=\"numero_mobile generica_italia\">";
strVar += "                            <div class=\"content\"><a href=\"tel:800003322\">800003322<\/a><\/div>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile generica_estero\">";
strVar += "                            <div class=\"content\"><a href=\"tel:+390282443333\">+390282443333<\/a><\/div>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile contestazioni_uno\">";
strVar += "                            <div class=\"content\"><a href=\"tel:0432744255\">0432744255<\/a><\/div>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile contestazioni_due\">";
strVar += "                            <div class=\"content\"><a href=\"tel:0432744264\">0432744264<\/a><\/div>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile contestazioni_tre\">";
strVar += "                            <div class=\"content\"><a href=\"tel:800.397206\">800.397206<\/a><\/div>";
strVar += "                            <span>(chiamate da telefono fisso)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile contestazioni_tre\">";
strVar += "                            <div class=\"content\"><a href=\"tel:02.30352001\">02.30352001<\/a><\/div>";
strVar += "                            <span>(chiamate da cellulare)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile contestazioni_quattro\">";
strVar += "                            <div class=\"content\"><a href=\"tel:06.72.280.735\">06.72.280.735<\/a><\/div>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile contestazioni_cinque\">";
strVar += "                            <div class=\"content\"><a href=\"tel:800.00.33.22\">800.00.33.22<\/a><\/div>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile furto_uno\">";
strVar += "                            <div class=\"content\"><a href=\"tel:800.90.21.22\">800.90.21.22<\/a><\/div>";
strVar += "                            <span>(dall'Italia)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile furto_uno\">";
strVar += "                            <div class=\"content\"><a href=\"tel:+39.049.2100.149\">+39.049.2100.149<\/a><\/div>";
strVar += "                            <span>(dall'estero)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile furto_due\">";
strVar += "                            <div class=\"content\"><a href=\"tel:800.652.653\">800.652.653<\/a><\/div>";
strVar += "                            <span>(dall'Italia)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile furto_due\">";
strVar += "                            <div class=\"content\"><a href=\"tel:+39.04.92100148\">+39.04.92100148<\/a><\/div>";
strVar += "                            <span>(dall'estero)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile furto_tre\">";
strVar += "                            <div class=\"content\"><a href=\"tel:800.207.167\">800.207.167<\/a><\/div>";
strVar += "                            <span>(dall'Italia)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile furto_tre\">";
strVar += "                            <div class=\"content\"><a href=\"tel:0039.0432.744106\">0039.0432.744106<\/a><\/div>";
strVar += "                            <span>(dall'estero)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile furto_quattro\">";
strVar += "                            <div class=\"content\"><a href=\"tel:800.822.056\">800.822.056<\/a><\/div>";
strVar += "                            <span>(dall'Italia)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile furto_quattro\">";
strVar += "                            <div class=\"content\"><a href=\"tel:0039.02.6084.3768\">0039.02.6084.3768<\/a><\/div>";
strVar += "                            <span>(dall'estero)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile furto_cinque\">";
strVar += "                            <div class=\"content\"><a href=\"tel:800.822.056\">800.822.056<\/a><\/div>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile furto_sei\">";
strVar += "                            <div class=\"content\"><a href=\"tel:06.72.900.347\">06.72.900.347<\/a><\/div>";
strVar += "                            <span>(dall'Italia)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile furto_sei\">";
strVar += "                            <div class=\"content\"><a href=\"tel:011.800.263.92.279\">011.800.263.92.279<\/a><\/div>";
strVar += "                            <span>(da USA, Canada e Australia)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile furto_sei\">";
strVar += "                            <div class=\"content\"><a href=\"tel:018.001.231.690\">018.001.231.690<\/a><\/div>";
strVar += "                            <span>(dal Messico)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile furto_sei\">";
strVar += "                            <div class=\"content\"><a href=\"tel:+800.263.92.279\">+800.263.92.279<\/a><\/div>";
strVar += "                            <span>(dagli altri paesi)<\/span>";
strVar += "                        <\/div>";
strVar += "                    <\/div>";
strVar += "                <\/div>";
strVar += "            <\/div>";
strVar += "            <!-- PosteVita -->";
strVar += "            <div class=\"panel\">";
strVar += "                <div class=\"panel-heading\" role=\"tab\" id=\"headingTwo\">";
strVar += "                    <h4 class=\"panel-title\">";
strVar += "                                <a class=\"accordion-toggle collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordionunique\" href=\"#collapse02\" aria-expanded=\"true\" aria-controls=\"collapseTwo\">PosteVita<\/a>";
strVar += "                            <\/h4>";
strVar += "                <\/div>";
strVar += "                <div id=\"collapse02\" class=\"panel-collapse collapse nojs-block\" role=\"tabpanel\" aria-labelledby=\"headingTwo\">";
strVar += "                    <div class=\"panel-body\">";
strVar += "                        <div class=\"numero_mobile n_postevita\">";
strVar += "                            <div class=\"content\"><a href=\"tel:800.31.61.81\">800.31.61.81<\/a><\/div>";
strVar += "                            <span>(numero attivo dal luned&igrave; al venerd&igrave; dalle 8:00 alle 20:00, sabato dalle 8:00 alle 14:00)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile n_posteassicura\">";
strVar += "                            <div class=\"content\"><a href=\"tel:800.13.18.11\">800.13.18.11<\/a><\/div>";
strVar += "                            <span>(numero attivo dal luned&igrave; al venerd&igrave; dalle 8:00 alle 20:00, sabato dalle 8:00 alle 14:00)<\/span>";
strVar += "                        <\/div>";
strVar += "                    <\/div>";
strVar += "                <\/div>";
strVar += "            <\/div>";
strVar += "            <!-- Servizi Postali -->";
strVar += "            <div class=\"panel\">";
strVar += "                <div class=\"panel-heading\" role=\"tab\" id=\"headingThree\">";
strVar += "                    <h4 class=\"panel-title\">";
strVar += "                                <a class=\"accordion-toggle collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordionunique\" href=\"#collapse03\" aria-expanded=\"false\" aria-controls=\"collapseThree\">Servizi Postali<\/a>";
strVar += "                            <\/h4>";
strVar += "                <\/div>";
strVar += "                <div id=\"collapse03\" class=\"panel-collapse collapse nojs-block\" role=\"tabpanel\" aria-labelledby=\"headingThree\">";
strVar += "                    <div class=\"panel-body\">";
strVar += "                        <div class=\"numero_mobile n_servizipostali\">";
strVar += "                            <div class=\"content\">";
strVar += "                                <a href=\"tel:+39 02.82.44.33.99\">+39 02.82.44.33.99<\/a>";
strVar += "                            <\/div>";
strVar += "                            <span>(numero attivo dal luned&igrave; al sabato dalle 8:00 alle 20:00)<\/span>";
strVar += "                        <\/div>";
strVar += "                    <\/div>";
strVar += "                <\/div>";
strVar += "            <\/div>";
strVar += "            <!-- Postemobile -->";
strVar += "            <div class=\"panel\">";
strVar += "                <div class=\"panel-heading\" role=\"tab\" id=\"headingFour\">";
strVar += "                    <h4 class=\"panel-title\">";
strVar += "                                <a class=\"accordion-toggle collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordionunique\" href=\"#collapse04\" aria-expanded=\"false\" aria-controls=\"collapseThree\">Postemobile<\/a>";
strVar += "                            <\/h4>";
strVar += "                <\/div>";
strVar += "                <div id=\"collapse04\" class=\"panel-collapse collapse nojs-block\" role=\"tabpanel\" aria-labelledby=\"headingFour\">";
strVar += "                    <div class=\"panel-body\">";
strVar += "                        <div class=\"numero_mobile servizioclienti_italia\">";
strVar += "                            <div class=\"content\"><a href=\"tel:160\">160<\/a><\/div>";
strVar += "                            <span>(gratuito dai numeri PosteMobile e dalla rete fissa Telecom Italia, attivo tutti i giorni dalle 7.00 alle 24.00 per assistenza tecnica, commerciale e amministrativa e 24 ore su 24 per furto\\/smarrimento)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile servizioclienti_estero\">";
strVar += "                            <div class=\"content\"><a href=\"tel:+39 37.70.00.01.60\">+39 37.70.00.01.60<\/a><\/div>";
strVar += "                            <span>(la chiamata ha il costo di una normale chiamata dall'estero verso l'Italia.)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile nonudenti_email\">";
strVar += "                            <div class=\"content\"><a class=\"mail\" href=\"mailto:servizioclienti_nonudenti@postemobile.it\">servizioclienti_nonudenti@postemobile.it<\/a><\/div>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile nonudenti_fax_italia\">";
strVar += "                            <div class=\"content\"><a href=\"tel:800 185 111\">800 185 111<\/a><\/div>";
strVar += "                            <span>(gratuito)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile nonudenti_fax_estero\">";
strVar += "                            <div class=\"content\"><a href=\"tel:+39 06.98.68.26.21\">+39 06.98.68.26.21<\/a><\/div>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile nonudenti_sms\">";
strVar += "                            <div class=\"content\"><a href=\"tel:40.71.164\">+40.71.164<\/a><\/div>";
strVar += "                            <span>(gratuito dall'Italia e dall'estero)<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile servizio_faidate\">";
strVar += "                            <div class=\"content\"><a href=\"tel:40.12.12\">40.12.12<\/a><\/div>";
strVar += "                            <span>attivo tutti i giorni 24 ore su 24 numero gratuito accessibile solo da SIM PosteMobile<\/span>";
strVar += "                        <\/div>";
strVar += "                    <\/div>";
strVar += "                <\/div>";
strVar += "            <\/div>";
strVar += "            <!-- Postemobile -->";
strVar += "            <div class=\"panel\">";
strVar += "                <div class=\"panel-heading\" role=\"tab\" id=\"headingFive\">";
strVar += "                    <h4 class=\"panel-title\">";
strVar += "                                <a class=\"accordion-toggle collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordionunique\" href=\"#collapse05\" aria-expanded=\"false\" aria-controls=\"collapseFive\">Postesalute<\/a>";
strVar += "                            <\/h4>";
strVar += "                <\/div>";
strVar += "                <div id=\"collapse05\" class=\"panel-collapse collapse nojs-block\" role=\"tabpanel\" aria-labelledby=\"headingFive\">";
strVar += "                    <div class=\"panel-body\">";
strVar += "                        <div class=\"numero_mobile n_postesalute\">";
strVar += "                            <div class=\"content\"><a href=\"tel:800.556.670\">800.556.670<\/a><\/div>";
strVar += "                            <span>(con operatore dal luned&igrave; al venerd&igrave;, dalle 09:00 alle 18:00 e il sabato dalle 09:00 alle 17:00 festivi esclusi. La chiamata &egrave; gratuita)<\/span>";
strVar += "                        <\/div>";
strVar += "                    <\/div>";
strVar += "                <\/div>";
strVar += "            <\/div>";
strVar += "            <!-- Postepay -->";
strVar += "            <div class=\"panel\">";
strVar += "                <div class=\"panel-heading\" role=\"tab\" id=\"headingSix\">";
strVar += "                    <h4 class=\"panel-title\">";
strVar += "                                <a class=\"accordion-toggle collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordionunique\" href=\"#collapse06\" aria-expanded=\"false\" aria-controls=\"collapseSix\">Postepay<\/a>";
strVar += "                            <\/h4>";
strVar += "                <\/div>";
strVar += "                <div id=\"collapse06\" class=\"panel-collapse collapse nojs-block\" role=\"tabpanel\" aria-labelledby=\"headingSix\">";
strVar += "                    <div class=\"panel-body\">";
strVar += "                        <div class=\"numero_mobile postepay_info_italia\">";
strVar += "                            <div class=\"content\"><a href=\"tel:800.00.33.22\">800.00.33.22<\/a><\/div>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile postepay_info_estero\">";
strVar += "                            <div class=\"content\"><a href=\"tel:+39 02.82.44.33.33\">+39 02.82.44.33.33<\/a><\/div>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile postepay_blocco_italia\">";
strVar += "                            <div class=\"content\"><a href=\"tel:800.90.21.22\">800.90.21.22<\/a><\/div>";
strVar += "                            <span>il servizio &egrave; attivo h24<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile postepay_blocco_estero\">";
strVar += "                            <div class=\"content\"><a href=\"tel:+39 049.21.00.149\">+39 049.21.00.149<\/a><\/div>";
strVar += "                            <span>il servizio &egrave; attivo h24<\/span>";
strVar += "                        <\/div>";
strVar += "                    <\/div>";
strVar += "                <\/div>";
strVar += "            <\/div>";
strVar += "            <!-- Mistral Air -->";
strVar += "            <div class=\"panel\">";
strVar += "                <div class=\"panel-heading\" role=\"tab\" id=\"headingSeven\">";
strVar += "                    <h4 class=\"panel-title\">";
strVar += "                                <a class=\"accordion-toggle collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordionunique\" href=\"#collapse07\" aria-expanded=\"false\" aria-controls=\"collapseSeven\">Mistral Air<\/a>";
strVar += "                            <\/h4>";
strVar += "                <\/div>";
strVar += "                <div id=\"collapse07\" class=\"panel-collapse collapse nojs-block\" role=\"tabpanel\" aria-labelledby=\"headingSeven\">";
strVar += "                    <div class=\"panel-body\">";
strVar += "                        <div class=\"numero_mobile mistralair_email\">";
strVar += "                            <div class=\"content\"><a href=\"mailto:infomistralair@posteitaliane.it\">infomistralair@posteitaliane.it<\/a><\/div>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile mistralair_fax\">";
strVar += "                            <div class=\"content\"><a href=\"tel:+39 06.59.19.567\">+39 06.59.19.567<\/a><\/div>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile mistralair_tel\">";
strVar += "                            <div class=\"content\"><a href=\"tel:+39 06.96.66.33.33\">+39 06.96.66.33.33<\/a><\/div>";
strVar += "                            <span>Da luned&igrave; a venerd&igrave; 9:00 - 13:00 e 14:00 - 18:00<\/span>";
strVar += "                        <\/div>";
strVar += "                        <div class=\"numero_mobile mistralair_posta\">";
strVar += "                            <div class=\"content\"><a href=\"javascript:void(0)\">Viale Lincoln, 3 00144 Roma (RM) - Italia<\/a><\/div>";
strVar += "                        <\/div>";
strVar += "                    <\/div>";
strVar += "                <\/div>";
strVar += "            <\/div>";
strVar += "        <\/div>";
strVar += "    <\/div>";
strVar += "<\/div>";




document.write(strVar);
